### ISSUE TITLE
Docs skeleton

### ISSUE THREAD

**Issue by jackparmer** [flojoy-io/docs#7]
# home page

https://docs.flojoy.io/

- [x] ⬅️ docs home page should have 3 prominent download buttons:
1. one for the windows electron distribution
2. one for the mac electron distribution
3. one to a docs page for how to install from source

look at other electron based apps for how they do this (vscode, slack, etc etc)

***

# "Getting started" section - Pages TODO

## Installation

https://docs.flojoy.io/getting-started/

- [ ] ⬅️ this page should be rewritten to only include the various ways of installing and updating the software

## Installation from source

- [ ] ⬅️ how to install the software without docker. this page should link from a "install from source" button on https://docs.flojoy.io/

## Creating your first app

- [ ] #19

## Creating your first CTRL panel

- [ ] ⬅️ extend the previous app to add a CTRL panel dashboard

## Loops & conditionals

- [x] ⬅️ overview of loops and conditionals in Flojoy and tutorial with a simple app that uses them

## Working with images

- [ ] ⬅️ Need to explain our approach to images

- [ ] ⬅️ Should have a few very simple demo apps that use images in different ways

(for example, from @dstrande)
<img width="671" alt="image" src="https://user-images.githubusercontent.com/1865834/223535840-d4346eae-e20c-4114-b7f2-81cb27cef2d8.png">

## Saving apps

- [ ] ⬅️ how to save flojoy apps to your computer

## Connecting to the physical world with `pymeasure`

- [ ] ⬅️ overview on how nodes can use `pymeasure` to read from instrumentation connected to the serial port. 

- [ ] ⬅️ need a few simple example DAQ apps... something like this
https://www.mathworks.com/help/supportpkg/arduinoio/ug/control-leds-1.html

- [ ] ⬅️ choose 1-2 good demos to recreate here also:
https://github.com/pymeasure/pymeasure/tree/master/examples

***

# "Advanced" section - Pages TODO

## API overview

- [ ] ⬅️ describe how passing transformed data from one node to the next works, using the `flojoy` Python library and `DataContainer` 

## Contributing nodes

- [ ] ⬅️ describe the steps and known gotchas for a Python developer who wants to create or edit their own node. target a developer who is just beginning Python. How to submit PRs with new Python nodes.

- [ ] ⬅️ include a link to a [pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) that includes:

- description of what the node does
- what are the node's inputs and outputs
- link to an example app for automatic testing (see next section)
- checklist of steps to successfully integrate the node into the framework

## Contributing apps 

- [ ] ⬅️ Guide for how to submit PRs that have new demo apps. 
- [ ] How the automatic app-based testing works.
- [ ] Include a link to a [pull request template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository) that includes:

- screenshot(s) and/or screencast(s) of example app
- description of what example app does

## Architecture overview

- [ ] ⬅️ Architecture diagram, libraries we use, agent-based modeling, etc @mdasifhasan 

## Developer setup

- [ ] ⬅️ Guide for new developers (staff or community) who want to contribute to the Flojoy full stack

## Installation on Rasberry Pi

- [ ] ⬅️ Does anyone have a Rasberry Pi to try this? 

*** 

# Tutorials section

- [x] DSP example @trbritt 
- [ ] PID example @trbritt 
- [ ] Webcam example @dstrande 
- [ ] Arduino example @dstrande 
- [ ] Function generator example 

Running list of more template app / tutorial ideas below:

https://github.com/flojoy-io/studio/issues/138

# Miscellaneous

- [ ] ⬅️ create a README template for app and node folders @jackparmer
